kind = "web"
previewPath = "/"
title = "Lab1 Website"
version = "1.0.0"
id = "artifacts/lab1-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18425

[services.development]
run = "pnpm --filter @workspace/lab1-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lab1-website", "run", "build" ]
publicDir = "artifacts/lab1-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18425"
BASE_PATH = "/"
